import { Activity } from "./types";

// This will be replaced by the database
export const MOCK_ACTIVITIES: Activity[] = [
    {
      id: 1,
      type: 'Research',
      title: 'Neuroscience Research MRI Study',
      creator: 'Dr. Smith',
      major: 'Neuroscience',
      year: 'Faculty',
      time: '9:00 AM Tomorrow',
      location: 'OSU Medical Center',
      distance: '0.8 miles',
      spots: 5,
      participants: 2,
      matchScore: 92,
      tags: ['Research', 'Neuroscience', 'Paid', 'MRI Study', 'Volunteering'],
      aiSuggestion: 'Great opportunity for psychology/neuroscience students',
      description: 'Participate in a 1-hour MRI study. Compensation provided.'
    },
    {
      id: 2,
      type: 'Club Meeting',
      title: 'AI Club Weekly Meeting',
      creator: 'AI Club President',
      major: 'Computer Science',
      year: 'All',
      time: '6:00 PM Today',
      location: 'Knowlton Hall 250',
      distance: '0.3 miles',
      spots: 50,
      participants: 20,
      matchScore: 85,
      tags: ['AI', 'Tech', 'Networking', 'Club Meeting'],
      aiSuggestion: 'Perfect for students interested in AI and machine learning.',
      description: 'Join us for a discussion on deep learning and AI trends.'
    },
    {
      id: 5,
      type: 'Study Group',
      title: 'CSE 2421 Study Session',
      creator: 'John Doe',
      major: 'Computer Science',
      year: 'Sophomore',
      time: '7:00 PM Tonight',
      location: 'Thompson Library 2nd Floor',
      distance: '0.0 miles',
      spots: 10,
      participants: 5,
      matchScore: 88,
      tags: ['Study', 'Computer Science', 'Midterms'],
      aiSuggestion: 'Great for students preparing for the upcoming CSE 2421 exam.',
      description: 'Join our study session to review concepts and solve problems together.'
    },

    {
      id: 4,
      type: 'Free Swag',
      title: 'Google Swag Giveaway',
      creator: 'Google Student Ambassadors',
      major: 'All Majors',
      year: 'All',
      time: '12:00 PM Tomorrow',
      location: 'Ohio Union',
      distance: '0.1 miles',
      spots: 100,
      participants: 40,
      matchScore: 90,
      tags: ['Tech', 'Networking', 'Free Swag'],
      aiSuggestion: 'Perfect for students looking for tech swag and networking.',
      description: 'Stop by to grab free Google swag and learn about career opportunities!'
    },
    {
      id: 6,
      type: 'Networking',
      title: 'Women in STEM Networking Night',
      creator: 'WiSTEM OSU',
      major: 'All STEM Majors',
      year: 'All',
      time: '6:30 PM Friday',
      location: 'Scott Lab 100',
      distance: '0.7 miles',
      spots: 30,
      participants: 15,
      matchScore: 95,
      tags: ['STEM', 'Women in Tech', 'Networking'],
      aiSuggestion: 'An excellent opportunity to meet fellow women in STEM and industry professionals.',
      description: 'Network with successful women in STEM fields and gain career advice.'
    },
  ];